### ISSUE TITLE
Performance penalty info

### ISSUE THREAD

**Issue by dzek69** [kozhevnikov/proxymise#2]
Proxies are still pretty slooooow. It would be nice to see how much of performance we're sacrificing by using this approach. Please add some benchmarks

**Comment by kozhevnikov** [comment]
Seems to have very little penalty on 10000 iterations.

```shell
node test/benchmark.js 
with proxymise: 3907.582ms
without proxymise: 3762.375ms
```

**Comment by dzek69** [comment]
Nice, thanks
